<?php

$modversion['name'] = '' . _CALENDEVENT . '';
$modversion['version'] = '2.24';
$modversion['description'] = '' . _CALENDEVENT_DESC . '';
$modversion['credits'] = 'Original version Don Grabowski<br>Don@ecomjunk.com';
$modversion['author'] = 'Xoops version Pascal Le Boustouller<br>webmaster@i-annonces.net<br>Kotshiro<br>InconnueTeam Webmaster<br>sylvain B.<br>InconnueTeam moderator<br>Webmaster Xoops V 2.0.7';
$modversion['license'] = 'GPL LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'eCal_logo.png';
$modversion['dirname'] = 'eCal';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Blocks
$modversion['blocks'][1]['file'] = 'eCal.php';
$modversion['blocks'][1]['name'] = '' . _CALENDEVENTRAND . '';
$modversion['blocks'][1]['show_func'] = 'eCal_rand';
$modversion['blocks'][2]['file'] = 'eCal.php';
$modversion['blocks'][2]['name'] = '' . _CALENDEVENTWEEK . '';
$modversion['blocks'][2]['show_func'] = 'eCal_week';
$modversion['blocks'][3]['file'] = 'eCal.php';
$modversion['blocks'][3]['name'] = '' . _CALENDEVENTMONTH . '';
$modversion['blocks'][3]['show_func'] = 'eCal_month';
$modversion['blocks'][4]['file'] = 'eCal.php';
$modversion['blocks'][4]['name'] = '' . _CALENDEVENTTODAY . '';
$modversion['blocks'][4]['show_func'] = 'eCal_today';
$modversion['blocks'][5]['file'] = 'eCal.php';
$modversion['blocks'][5]['name'] = '' . _CALENDEVENTNEXTN . '';
$modversion['blocks'][5]['show_func'] = 'eCal_nextn';
$modversion['blocks'][6]['file'] = 'eCal.php';
$modversion['blocks'][6]['name'] = '' . _CALENDEVENTM . '';
$modversion['blocks'][6]['show_func'] = 'eCal_showm';

// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _ADD_EVENT;
$modversion['sub'][1]['url'] = 'addevent.php';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";
// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'eCal';
